### ISSUE TITLE
Add compatibility for Gradle 8

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/pulumi-java#1004]
Related to CI failures which were resolved by https://github.com/pulumi/ci-mgmt/pull/352

**Comment by dixler** [comment]
Hey @danielrbradley was this not resolved by

- https://github.com/pulumi/pulumi-java/pull/1002

**Comment by danielrbradley** [comment]
Ah looks like it might be fixed by that. Guess the issue was already closed when I was searching. Any plan around the release going out with this?
