### ISSUE TITLE
Update azure-native to use full schema

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-java#103]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

It turns out that pulumi-azure-native only publishes abbreviated schema to GitHub, not the full schema.

```
[nix-shell:~/pulumi-java]$ du -sh ~/schemas/*.json
du -sh ~/schemas/*.json
184M	/Users/anton/schemas/pulumi-azure-native-v1.56.0-full.json
34M	/Users/anton/schemas/pulumi-azure-native-v1.56.0.json
```

The provider does carry the full schema inside though.

The task would be to upgrade the builds here to use the full schema.

How to obtain the schema: with https://github.com/pulumi/pulumi/pull/8909 we can do:

```
./pulumi schema extract azure-native 1.56.0 > ~/schemas/pulumi-azure-native-v1.56.0-full.json 
```

Then editing the appropriate pulumi-java-gen.yaml to point to this schema does the trick.

I've took this for a spin on my machine. Findings:

- pulumi-java-gen is extremely memory hungry ~2GB but eventually finishes without errors; this is a great stress-tets
- gradle build runs out of memory with 4GB heap
- with 8GB heap it's heating up my machine but proceeding, then failed: BUILD FAILED in 16m 47s
- we might need to rethink the compilation or project layout to scale to this size

**Comment by t0yv0** [comment]
Possibly should be part of GA. Waiting on Paul's team potential solutions with breaking up the schema.

**Comment by mikhailshilkov** [comment]
Deferring this to providers
