### ISSUE TITLE
Pulumi Java - Examples with Map(java.Map) not working

### ISSUE THREAD

**Issue by marctree** [pulumi/pulumi-java#1039]
### Discussed in https://github.com/pulumi/pulumi/discussions/12469

<div type='discussions-op-text'>

<sup>Originally posted by **marctree** March 22, 2023</sup>
Hi folks,

i tried to create a infrastructure in azure cloud with pulumi java. Unfortunately i came across some wierd errors when i try to deploy a e.g. storage account or a key vault which are using "import java.util.Map;". I get always a compile error -> 

Method com.pulumi.azurenative.storage.StorageAccountArgs.Builder.encryption(com.pulumi.core.Output<com.pulumi.azurenative.storage.inputs.EncryptionArgs>) is not applicable
          (No matching arguments, No instances of type variables K,V,K,V,K,V,K,V,K,V,V,K,V,V,K,V,K,V,V,K,V,V,K,V,V,V,V,K,V, so java.util.Map<K,V> matches com.pulumi.core.Output<com.pulumi.azurenative.storage.inputs.EncryptionArgs>.

The example im using is this one here (StorageAccountCreate)-> https://www.pulumi.com/registry/packages/azure-native/api-docs/storage/storageaccount/

I init my pulumi project with the standard values so i dont have to change anything in the code. Still i got this error as long as the Map is in the code. When i delete the Map it works fine. Do i miss something here?

Thank you for your answers!
cheers</div>

**Comment by marctree** [comment]
Hi @Zaid-Ajaj thank you for your answer! I will test it again. Thank you for your help!

**Comment by Zaid-Ajaj** [comment]
@marctree We no longer generate `Map` for nested objects, this was an issue where the type of the object wasn't properly resolved but it is now. Closing as resolved
