### ISSUE TITLE
:jar fails for large SDKs

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/pulumi-java#1087]
When attempting to package the Java SDK for azure-native v2 the build fails with the following message:

```
> Task :jar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jar'.
> archive contains more than 65535 entries.
```

Is there any way to get around this problem by reducing the number of files or increasing the maximum number of files in a package?

**Comment by justinvp** [comment]
This was recently fixed for `pulumi-aws` with https://github.com/pulumi/pulumi-java/pull/1068.

**Comment by danielrbradley** [comment]
Looks like that was only the javadoc task ... will test locally if applying the same fix can apply.
