### ISSUE TITLE
Third Party Publishers not supported

### ISSUE THREAD

**Issue by muhlba91** [pulumi/pulumi-java#1118]
### What happened?

not using `Pulumi` as the publisher in `resources.go` leads to an incomplete `build.gradle` file.

specifically the publishing configuration:
```java
publishing {
    publications {
        mainPublication(MavenPublication) {
            groupId = ""
            artifactId = ""
            version = resolvedVersion
            from components.java
            artifact sourcesJar
            artifact javadocJar

            pom {
                inceptionYear = ""
                name = ""
                packaging = "jar"
                description = ""

                url = "https://github.com/muhlba91/pulumi-proxmoxve"

                scm {
                    connection = "git@github.com/muhlba91/pulumi-proxmoxve.git"
                    developerConnection = "git@github.com/muhlba91/pulumi-proxmoxve.git"
                    url = "https://github.com/muhlba91/pulumi-proxmoxve"
                }

                licenses {
                    license {
                        name = "The Apache License, Version 2.0"
                        url = "http://www.apache.org/licenses/LICENSE-2.0.txt"
                    }
                }

                developers {
                    developer {
                        id = ""
                        name = ""
                        email = ""
                    }
                }
            }
        }
    }
}
```

in comparison the GCP provider sets `Pulumi` as publisher and ends up with correct parameters: https://github.com/pulumi/pulumi-gcp/blob/master/sdk/java/build.gradle#LL79C1-L120C2

the reason is a hard-coded check for `Pulumi` publishers in https://github.com/pulumi/pulumi-java/blob/main/pkg/codegen/java/templates_gradle.go#L119-L130.

### Expected Behavior

auto-generation of java code and `build.gradle` supports using a third-party publisher, e.g. by setting the required parameters in the `JavaBridge` in `resources.go`. (= parameters in https://github.com/pulumi/pulumi-java/blob/main/pkg/codegen/java/templates_gradle.go#L119-L130 can be sourced from the config)

### Steps to reproduce

1. set the `Publisher` property in `resources.go` to something else than `Pulumi`
2. trigger code-generation

### Output of `pulumi about`

N/A

### Additional context

example of a current WIP third-party provider supporting Java is https://github.com/muhlba91/pulumi-proxmoxve/pull/65

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dixler** [comment]
Thanks for filing this and providing a lot of detail. Taking a look!

**Comment by dixler** [comment]
We'll be cutting a release of pulumi-java tomorrow which will contain the fix for this issue. We greatly appreciate your feedback! Let us know if you run into any other issues!
