### ISSUE TITLE
 invalid JSON: invalid character '\n' in string literal when using Kotlin variable in string

### ISSUE THREAD

**Issue by dkittle** [pulumi/pulumi-java#1183]
### What happened?

When I try to include a variable in a Kotlin string, Pulumi reports a problem with the resource saying:

```
Diagnostics:
  aws:s3:BucketPolicy (b4b-Dev-website-policy):
    error: aws:s3/bucketPolicy:BucketPolicy resource 'b4b-Dev-website-policy' has a problem: "policy" contains an invalid JSON: invalid character '\n' in string literal. Examine values at 'b4b-Dev-website-policy.policy'.
```

The code for the bucket policy is:
```
val bucketPolicy = bucketPolicy("b4b-${env.name}-website-policy") {
        args {
            bucket(source.id)
            policy("{\"Version\": \"2012-10-17\", \"Statement\": [{ \"Sid\": \"PublicReadGetObject\", \"Effect\": \"Allow\", \"Principal\": \"*\", \"Action\": \"s3:GetObject\", \"Resource\": \"${source.arn}/*\" }]}") // ktlint-disable max-line-length
        }
    }

```

### Expected Behavior

I would have expected I could include a variable within a string that describes the bucket policy. Without being able to do that, I'm not sure how I can supply the bucket arn as part of the policy.

### Steps to reproduce

Use the code above to add a policy to an S3 bucket. If I remove the variable, the code will work fine. If I use `" + source.arn +"`, I get the same error about a \n in the json.

### Output of `pulumi about`

CLI          
Version      3.78.1
Go Version   go1.20.7
Go Compiler  gc

Plugins
NAME  VERSION
aws   5.42.0
java  unknown

Host     
OS       darwin
Version  13.4.1
Arch     arm64

This project is written in java: executable='/usr/bin/java' version='openjdk 19 2022-09-20
OpenJDK Runtime Environment (build 19+36-2238)
OpenJDK 64-Bit Server VM (build 19+36-2238, mixed mode, sharing)' java='/usr/bin/java' javac='19' maven='Apache Maven 3.9.0 (9b58d2bad23a66be161c4664ef21ce219c2c8584)'

Current Stack: donkittle/dmseer-infra/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/dkittle
User           dkittle
Organizations  dkittle, donkittle

No dependencies found

Pulumi locates its logs in /var/folders/_1/bfwdf3td0xdd3ntzws9r8mtw0000gn/T/ by default

### Additional context

I am using Kotlin with these dependencies:

```
    implementation("com.pulumi:pulumi:0.9.4")
    implementation("org.virtuslab:pulumi-aws-kotlin:5.42.0.0")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("org.jetbrains.kotlin:kotlin-reflect")

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Zaid-Ajaj** [comment]
Hi there @dkittle from what I see in the example code above is that you are using `source.arn` directly as part of a string literal. I believe `source.arn` is of type `Output<string>` which means that you cannot use it as a value directly, instead you use its value from an `applyValue` call as follows. 
```kotlin
val bucketPolicyJson = source.arn.applyValue(fun(arn: String): String {
    return "{\"Version\": \"2012-10-17\", \"Statement\": [{ \"Sid\": \"PublicReadGetObject\", \"Effect\": \"Allow\", \"Principal\": \"*\", \"Action\": \"s3:GetObject\", \"Resource\": \"${arn}/*\" }]}";
})

val bucketPolicy = bucketPolicy("b4b-${env.name}-website-policy") {
    args {
        bucket(source.id)
        policy(bucketPolicyJson)
    }
}
```
Can you give this a try?
