### ISSUE TITLE
Java SDK panics when missing required property

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-java#1199]
### What happened?

See https://github.com/pulumi/pulumi-rke/issues/129 for the user facing issue. Basically, the user didn't provide a required field, and they got a `java.lang.NullPointerException: expected parameter 'user' to be non-null`. This exception sounds like we have dereferenced a null pointer (which I assume we have).

### Expected Behavior

We don't throw `java.lang.NullPointerException`s. If the user failed to supply a required input, we should throw a Pulumi exception: `com.pulumi.MissingRequiredProperty`[^1] that clearly indicates that this is a user problem and how they should address it. 

Missing arguments should never result in a null pointer exception.

[^1]: I'm not saying it should be that name in particular, but it should definitely be from the Pulumi namespace, not `java.lang`.

### Steps to reproduce

See https://github.com/pulumi/pulumi-rke/issues/129

### Output of `pulumi about`

```
CLI          
Version      3.78.1
Go Version   go1.20.7
Go Compiler  gc

Plugins
NAME  VERSION
java  unknown

Host
OS       Microsoft Windows 11 Enterprise
Version  10.0.22000 Build 22000
Arch     x86_64

This project is written in java: executable='' version='openjdk 19 2022-09-20
OpenJDK Runtime Environment (build 19+36-2238)
OpenJDK 64-Bit Server VM (build 19+36-2238, mixed mode, sharing)' java='' javac='19'

Current Stack: organization/infrastructure/dev

TYPE                                               URN
pulumi:pulumi:Stack                                urn:pulumi:dev::infrastructure::pulumi:pulumi:Stack::infrastructure-dev
pulumi:providers:docker                            urn:pulumi:dev::infrastructure::pulumi:providers:docker::default_4_3_1
docker:index/remoteImage:RemoteImage               urn:pulumi:dev::infrastructure::docker:index/remoteImage:RemoteImage::ubuntuRemoteImage
com.myproject.infrastructure:core:cluster:Rancher  urn:pulumi:dev::infrastructure::com.myproject.infrastructure:core:cluster:Rancher::RancherDeployment
pulumi:providers:rke                               urn:pulumi:dev::infrastructure::pulumi:providers:rke::default_3_3_0
rke:index/cluster:Cluster                          urn:pulumi:dev::infrastructure::com.myproject.infrastructure:core:cluster:Rancher$rke:index/cluster:Cluster::rancher-cluster
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
I wouldn't call this prioritized as impact/panic since the error clearly indicates what the problem is; changing the class of the error is an enhancement.
