### ISSUE TITLE
Consider removing Deployment callVoid

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-java#122]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Consider removing `callVoid` forms. 

These really are async methods but the `void` form makes it look like fire-and-forget. This got copied from the C# SDK, where it's exported but not used internally. Not knowing the use cases, the intuition would suggest that returning Output or CompletableFuture would steer the user to consider awaiting the result so that the calling code synchronizes, which feels like the safer default. The user can still fire-and-forget by ignoring the output, but the type signature matters. 

If there's use cases where returning void is really a lot preferable I'd love to understand those.

```java
    /**
     * Same as {@link #call(String, TypeShape, CallArgs, Resource, CallOptions)}, however the return value is ignored.
     */
    void callVoid(String token, CallArgs args, @Nullable Resource self, @Nullable CallOptions options);

    /**
     * Same as {@link #call(String, TypeShape, CallArgs, Resource, CallOptions)}, however the return value is ignored.
     */
    void callVoid(String token, CallArgs args, @Nullable Resource self);

    /**
     * Same as {@link #call(String, TypeShape, CallArgs, Resource, CallOptions)}, however the return value is ignored.
     */
    void callVoid(String token, CallArgs args);
```

### Steps to reproduce

1.
2.
3.
4.

Expected: 
Actual:

**Comment by pawelprazak** [comment]
Should we go forward with this change?

**Comment by t0yv0** [comment]
This is done.
