### ISSUE TITLE
Add the cockroach (DB) provider

### ISSUE THREAD

**Issue by kylepl** [pulumi/pulumi-java#1260]
## Hello!
- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I'm trying to use Cockroach DB, actually through the experimental Kotlin support, but that requires the Java implementation. See discussion here: https://github.com/VirtuslabRnD/pulumi-kotlin/pull/390#issuecomment-1783413845.

I'm referring to this provider: https://www.pulumi.com/registry/packages/cockroach/

I don't have a sense of how tricky it is to add.

**Comment by Frassle** [comment]
You need to raise this as an issue at https://github.com/lbrlabs/pulumi-cockroach to get a java SDK published for that provider. This repo is not responsible for ensuring sdks are published for all individual providers.

**Comment by kylepl** [comment]
Ack, thanks!
