### ISSUE TITLE
Ignore or escape unintended javadoc comments 

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/pulumi-java#1271]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Pulumi-GCP v7.1.0 introduced what we believe is a spurious extra string to the description of a few resources. This string started with `@pattern: ` and was populated to the documentation sections in the Pulumi schema and picked up by all related resources
see [Csharp example](https://github.com/pulumi/pulumi-gcp/blob/v7.1.0/sdk/dotnet/Compute/ForwardingRule.cs#L370) in all SDKs.

All SDKs build successfully and passed integration tests, so the upgrade was merged and released.

However, during the SDK publish step, the [Java publish failed](https://github.com/pulumi/pulumi-gcp/actions/runs/6881931301/job/18728079843#step:3:2872) because Javadoc was interpreting this spurious string as a doc tag.

It would be fantastic if we could allow only a subset of expected Javadoc tags, and escape anything not on this allowlist.

### Affected area/feature

SDK publication

**Comment by t0yv0** [comment]
I've just reverted this in https://github.com/pulumi/pulumi-java/pull/1345 - I apologize if I'm a bit revert-happy here - the reasoning is that we found another blocker for azure builds and also a seeming regression from this change - I'm not 100% sure and it might be a separate issue and this change here was fixing the original issue as stated. However it would be nice to just get this javadoc escaping right before releasing a new version.
