### ISSUE TITLE
Invalid homepage and publisher

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-java#1366]
### What happened?

We were diagnosing issues in package publishing. @mikhailshilkov found that Publishing to java requires that:
- The homepage found in the schema doesn't have `www.`.
- The publisher found in the schema is not capitalized.

Ideally

### Example

You can see an example of the needed changes [here](https://github.com/pulumi/pulumi-dbtcloud/pull/23/files) or [here](https://github.com/pulumi/pulumi-docker-build/pull/89) (where we needed to fix it).

It looks like we will also need fixes in:
- https://github.com/pulumi/pulumi-scm/blob/ce6b781e09f82422fdcb7446bb8fc3509cefb02d/provider/resources.go#L58
- https://github.com/pulumi/pulumi-ise/blob/3e53d2d92267f05c190ffd1960a130cd9a06ebc0/provider/resources.go#L150
- https://github.com/pulumi/pulumi-sdwan/blob/262543eac8fd9e7faf9fed9298f35a9c9b3399d7/provider/resources.go#L58
- https://github.com/pulumi/pulumi-meraki/blob/86be07c3f3a0b531b3e52d9214671b1226377270/provider/resources.go#L135

Ideally, SDK generation will fix up the metadata so publishing will succeed. If publishing will fail, SDK generation should fail. It might not be possible to validate that the publisher will match but it is possible to validate that the homepage is valid.

### Output of `pulumi about`

NA

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
I think we could update this check to allow any case `pulumi` and `www` in the URL.

https://github.com/pulumi/pulumi-java/blob/0f614b60a861e9e2faa2f798036dda6fddb4dba4/pkg/codegen/java/templates_gradle.go#L126-L129
