### ISSUE TITLE
ClassLoader loads all packages presented in pom

### ISSUE THREAD

**Issue by andreaspartisia** [pulumi/pulumi-java#1385]
### What happened?

We used a packages wihich contains other not used packages, so these packages is not loaded by maven and therefore  the class loader has a problem to load it. This will some out as a error on packages problem:
    SEVERE: Running program [PID: 13236](unknown) failed with an unhandled exception:
    java.lang.IllegalStateException: Failed to load class 'org.apache.commons.compress.harmony.pack200.NewAttribute$ErrorAttribute' (package: 'org.apache.commons.compress.harmony.pack200') from class path: org/objectweb/asm/Attribute

### Example

It is pom.xml excluding a package. We would like to only de it sometimes, because we have multiple class providers etc.   
 <dependency>
      <groupId>com.github.docker-java</groupId>
      <artifactId>docker-java-core</artifactId>
      <exclusions>
        <exclusion>
          <groupId>org.apache.commons</groupId>
          <artifactId>commons-compress</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

### Output of `pulumi about`

CLI          
Version      3.112.0
Go Version   go1.22.1
Go Compiler  gc

Plugins
NAME        VERSION
aws         6.40.0
command     0.10.0
eks         2.7.1
java        unknown
kubernetes  4.13.1

Host
OS       Microsoft Windows 11 Pro
Version  10.0.22631 Build 22631
Arch     x86_64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Thanks for the suggestion and PR. I left some comments.
