### ISSUE TITLE
Build failing with `error: malformed HTML`

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-java#1408]
### What happened?

```
/home/runner/work/pulumi-docker/pulumi-docker/sdk/java/src/main/java/com/pulumi/docker/Image.java:290: error: malformed HTML
     * The manifest digest of an image pushed to a registry, of the format repository{@literal @}<algorithm&gt;:&lt;hash&gt;, e.g. `username/demo-image{@literal @}sha256:a6ae6dd8d39c5bb02320e41abf00cd4cb35905fec540e37d306c878be8d38bd3`.
                                                                                                 ^
```

### Example

This was discovered when testing pulumi-terraform-bridge v3.89.0-candidate on docker:

https://github.com/pulumi/pulumi-docker/actions/runs/10307662375/job/28533381889

I have confirmed that this issue is not present on 0.12.0.

### Output of `pulumi about`

NA

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
@lunaris, possibly due to https://github.com/pulumi/pulumi-java/pull/1397?
