### ISSUE TITLE
Lambda-based Builder pattern

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-java#151]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Based on discussion in https://github.com/pulumi/pulumi-java/pull/140

Using lambda-based patterns in builders avoids a slew of imports and name clash issues, e.g.:

```
Profile.of("blah", pb -> pb
    .setResourceGroupName(resourceGroup.getName())
    .setLocation("global")
    .setSku(sb -> sb.setName("name")) /// avoid referencing/importing Sku.Builder() since we can bind it in a lambda
);
```

We should try this out and verify completion experience is decent in a Java IDE like IDEA and/or Eclipse. Linking any prior art of other projects using this pattern would also be helpful.

**Comment by therealppa** [comment]
So did anything come out of this? I would agree that the Lambda-based builder is a but unusual in Java but anything that reduces the boilerplate is definitely welcome! pulumi-java with all the builders is quite heavy and looking at the code makes me want to write wrappers for everything, which can't be a good idea.

**Comment by t0yv0** [comment]
@therealppa we've experimented with it and had a working implementation but decided against including it after doing a survey of Java styles of other products in this space. The current API is indeed on the verbose side but it's entirely unsurprising and IDEs code-complete it well. Our team is a bit too light on Java expertise at the moment so we're also waiting for some strong community input and contributions on how the API can be done better.

**Comment by therealppa** [comment]
@t0yv0 Understandable, and I can agree that it works well in the aspects you listed. Thanks!
