### ISSUE TITLE
Restore working pulumi import command for Java

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-java#17]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

With #12 we are losing some of Pawel's changes to pulumi/pulumi that let `pulumi import` hook into Java programgen. This needs a different solution since pulumi/pulumi should not build-depend on pulumi/pulumi-java. Basically we need a mechanism for the CLI to dynamically discover the Java programgen code and ask it to generate code.

```
git diff pulumi-fork-point..d302f9c049ac7a9653d56e9073ca3f091be0ace9 -- pkg/cmd/pulumi/import.go

diff --git a/pkg/cmd/pulumi/import.go b/pkg/cmd/pulumi/import.go
index 2e86e8f91..f3a577c60 100644
--- a/pkg/cmd/pulumi/import.go
+++ b/pkg/cmd/pulumi/import.go
@@ -34,6 +34,7 @@ import (
 	gogen "github.com/pulumi/pulumi/pkg/v3/codegen/go"
 	"github.com/pulumi/pulumi/pkg/v3/codegen/hcl2"
 	"github.com/pulumi/pulumi/pkg/v3/codegen/importer"
+	"github.com/pulumi/pulumi/pkg/v3/codegen/jvm"
 	"github.com/pulumi/pulumi/pkg/v3/codegen/nodejs"
 	"github.com/pulumi/pulumi/pkg/v3/codegen/python"
 	"github.com/pulumi/pulumi/pkg/v3/codegen/schema"
@@ -436,6 +437,8 @@ func newImportCmd() *cobra.Command {
 			switch proj.Runtime.Name() {
 			case "dotnet":
 				programGenerator = dotnet.GenerateProgram
+			case "jvm":
+				programGenerator = jvm.GenerateProgram
 			case "go":
 				programGenerator = gogen.GenerateProgram
 			case "nodejs":

```

**Comment by mikhailshilkov** [comment]
Has this been done?

**Comment by Frassle** [comment]
Yup https://github.com/pulumi/pulumi/blob/master/pkg/cmd/pulumi/import.go#L466
