### ISSUE TITLE
Converter issues prevent catching up with pulumi master

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-java#175]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

> Blocked from porting next batch of versions, because of converter issues.

TBD expand with repro / more detail.

### Steps to reproduce

1.
2.
3.
4.

Expected: 
Actual:

**Comment by mikhailshilkov** [comment]
Is this still up-to-date? We haven't touched it for months but it sounds scary.

**Comment by pawelprazak** [comment]
I think we can close this one. 

At the time I was trying to port changes from dotnet SDK, done since forking, to catch up with upstream, 
but I'm afraid the implementations has diverged enough that this approach will no longer work.

**Comment by t0yv0** [comment]
Yes, happy to close this one. The issue is scoped too broadly so it's tough.

The specific case of #8286 change is this. C# SDK proceeds with a `null` or `defaultof(T)` and a warning instead of throwing in the case it cannot understand and correctly deserialize a value coming out of grpc into a the in-mem C# typed representation it expects. Before #8286 it used to throw. 

It provides a degree of error tolerance when schemas are wrong, and it was needed for some reason.

Let me file it up in the tracker.
