### ISSUE TITLE
Pulumi Homepage example

### ISSUE THREAD

**Issue by dixler** [pulumi/pulumi-java#364]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
@susanev mentioned that we need to send them a java example of the use-case on the pulumi homepage to put on the pulumi homepage.
![image](https://user-images.githubusercontent.com/25750473/162461621-cec8da7a-ca81-47d5-bfe8-7645212c2c2d.png)

**Comment by t0yv0** [comment]
I believe @susanev built a lovely example that's featured on pulumi.com now.
