### ISSUE TITLE
Deserialization should not rely on classes with constructors having large parameter counts

### ISSUE THREAD

**Issue by dixler** [pulumi/pulumi-java#390]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Deserialization should not rely on classes with constructors having large parameter counts.

Code generation for Java SDK classes that need to be deserialized from protobuf currently relies on constructors with many parameters (one per desired property) internally. This breaks down when it hits hard limits on Java parameter counts. 

Earlier when we worked around the problem of not being able to compile providers with large parameter counts, we introduced a special pathway in the SDK code generator for the special case of "jumbo" constructors. This does not completely solve the problem however. While you can construct these Jumbo objects, tryConvertObjectInner errors when facing them.

Desired complete fix would:

- [x] fix the deserializer in the Java SDK to not require one parameter per property in any method or constructor of the generated classes, so as to not hit the Java limit
- [ ] fix the codegen to align with the deserializer expectations
- [ ] remove branching on parameter count from codegen code
- [ ] have no breaking changes for the users (it seems the problem can be solved internally)
- [ ] fix or avoid "`Converter::tryConvertObjectInner` errors when calling jumbo constructors"  found earlier

**Comment by pawelprazak** [comment]
I've [added jumbo custom type support to the SDK](https://github.com/pulumi/pulumi-java/pull/720), it is already quite big (because of codegened test) 
so it feel like I should do the codegen changes in a separate PR, WDYT?

**Comment by pawelprazak** [comment]
I assume we don't want to break current providers, so I plan to remove the constructor-based code, after we release both the new codegen and regenerate all of the (affected) providers.

As a result, I plan to do as follows, in 4 stages:
- SDK change (https://github.com/pulumi/pulumi-java/pull/720), release the SDK
- update codegen to use the new mechanism
- regenerate and release providers with the new codegen
- remove the old mechanism from codegen and from SDK

**Comment by t0yv0** [comment]
Let's create a follow-up issue (s) for cleanup issues, and consider this done.
