### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-java#529]
We need a language specific docker image for Java, as well as a java SDK adding to the "full" pulumi Docker image

**Comment by pawelprazak** [comment]
Could you give me a pointer to an existing one that will be a good example of the expected outcome?

**Comment by stack72** [comment]
Yea that's exactly correct @t0yv0

**Comment by dixler** [comment]
which docker base image do we want to use(I'm assuming java 11 since our docs say java 11 or later)
https://hub.docker.com/_/openjdk?tab=tags&page=1&name=11

@stack72 @jaxxstorm
