### ISSUE TITLE
StackReferenceArgs missing `T` overload

### ISSUE THREAD

**Issue by dixler** [pulumi/pulumi-java#534]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
Missed adding an overload to StackReferenceArgs.

StackReference can accept a plain string if the reference is passed as the first argument, but if the Args builder is used it only takes an output. Should be an easy fix.

https://github.com/pulumi/pulumi-java/blob/main/sdk/java/pulumi/src/main/java/com/pulumi/resources/StackReferenceArgs.java

**Comment by pawelprazak** [comment]
What is the expected change?

Currently we have:
```java
StackReference(String name) // that takes
```
That does this underneath:
```java
   private static Output<String> ensureName(@Nullable StackReferenceArgs args, String name) {
        return args == null ? Output.of(name) : args.getName().orElse(Output.of(name));
    }
``` 

I assume, what is requested in this issue, is to add `StackReferenceArgs.builder()` and `StackReferenceArgs.Builder` with the overloaded setter, is that right?
