### ISSUE TITLE
Provider updates

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-java#543]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

- https://github.com/pulumi/pulumi-java/pull/561
- Azure 5.5.0
- https://github.com/pulumi/pulumi-java/pull/560
- https://github.com/pulumi/pulumi-java/pull/562
- https://github.com/pulumi/pulumi-java/pull/566
- https://github.com/pulumi/pulumi-java/pull/563
- https://github.com/pulumi/pulumi-java/pull/565
- https://github.com/pulumi/pulumi-java/pull/567

**Comment by t0yv0** [comment]
Tagged these, should be on Maven Central shortly.

```
Provider update: aws 5.4.0
Provider update: gcp 6.23.0
Provider update: azuread 5.22.0
Provider update: random 4.6.0
Provider update: kubernetes 3.19.1
Provider update: google native 0.18.2
```

Awaiting review on azure-native PR. 

Azure classic needs to be added separately: 
https://github.com/pulumi/pulumi-java/issues/572

**Comment by pawelprazak** [comment]
Related #579
