### ISSUE TITLE
Add mock (unit) testing Java example

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-java#553]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

This would illustrate how to do https://www.pulumi.com/docs/guides/testing/ for Java.  See the Unit Testing section that mentions examples in other languages. We would first add an examples and then add Java reference to tag page. Note that APIs used for "unit" testing Pulumi programs need to become stable, so we might need to review these APIs before taking a further commitment.

@pawelprazak mentioned that mockito dependency is unfortunate, perhaps that can be avoided.

**Comment by pawelprazak** [comment]
Note to self: fix #419 after this one.

**Comment by pawelprazak** [comment]
API that I'm working on:
```
PulumiTest.withOptions(new TestOptions(false))
  .monitorMocks(new MocksTest.MyMocks())
  .useMockRunner() // vs .useRealRunner()
  .build()
```

```
    /**
     * Run a Pulumi test stack callback asynchronously and return an exit code.
     *
     * @param stack the stack to run in Pulumi test runtime
     * @return a future exit code from Pulumi test runtime after running the stack
     */
    CompletableFuture<Integer> runAsync(Consumer<Context> stack);

    /**
     * Run a Pulumi test stack callback asynchronously and return {@link TestResult}.
     *
     * @param stack the stack to run in Pulumi test runtime
     * @return a future {@link TestResult} from Pulumi test runtime after running the stack
     */
    CompletableFuture<TestResult> runTestAsync(Consumer<Context> stack);
```

```
public class TestResult {

    private final int exitCode;
    private final List<Exception> exceptions;
    private final List<Resource> resources;
    private final List<String> errors;
    private final Stack stack;
    ...
}
```

There will also be `PulumiTestInternal` with a lot more API surface area for internal testing purposes, in fact, `PulumiTest` is just an interface that limits the internal one to the externally useful subset.

I'm also leaning towards having `.useRealRunner()` as the default and `.useMockRunner()` as an option, but I don't have a strong opinion on that one.

The fact that we set a global singleton is an implementation detail, and it is also true for the `Pulumi.run` itself, and not specific to the test API, so we should document it but making is as part of API does not feel like thinking ahead, esp. since we may change this in the future.

**Comment by pawelprazak** [comment]
An advanced, internal test would look similar to (this was a work in progres version but close to what I have in mind): https://github.com/pulumi/pulumi-java/pull/590/files#diff-2fd8390afc1feee0a2d9b1064a0378ac8a486ca7c33716e8c42a0a39d803e804R39

**Comment by t0yv0** [comment]
And include ideas how to clean up the mock testing API.

**Comment by t0yv0** [comment]
See https://github.com/pulumi/pulumi-java/pull/591#issuecomment-1137386366 with what's possible now and current pain-points.

**Comment by t0yv0** [comment]
Curious, CallArgs and ResourceArgs are empty classes - I'm not sure actually we even use them or need them. Unifying them with MockCallArgs may be possible but we need to expose the structure that MockCallArgs exposes for the test logic for example. This may have implications for prod logic but may be workable.
