### ISSUE TITLE
Add aws-apigateway SDK

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-java#564]
In the work to translate our AWSX annoucement examples to Java (https://github.com/pulumi/platform-providers-team/issues/50), there's no Java SDK for [pulumi/pulumi-aws-apigateway](https://github.com/pulumi/pulumi-aws-apigateway). Can we add a Java SDK for this provider?

**Comment by pawelprazak** [comment]
There's a small issue, the schema is in yaml not json, so the current codegen can't consume it.
