### ISSUE TITLE
Enable ability to add Java support to external repos

### ISSUE THREAD

**Issue by stack72** [pulumi/pulumi-java#583]
As part of the post Java preview launch, we now need to add the ability to allow 1st and 3rd part providers to add Java support to their providers 

we have decided on centralising all of the Java logic in a Central Java repo and building a generation binary that is available for download for use in our package repos

Currently, the Java-gen binary takes a config file necessary to create the SDK code. Most of those arguments are not going to be required as part of the generation within a specific provider repository. Therefore, we should allow the Java gen binary to accept cli arguments of provider name, version (reading from environment variable would be amazing) and a list of dependencies (when an MLC for example).

The Java gen binary should be able to generate the Graeme / maven build files as part of the codegen so they don’t need to be manually created

The process for Java gen would be to download the latest binary in each parameter (the binary should adhere to Semver!) and be in control of the dependencies needed for Java SDK generation

we then also need to understand the secrets and build steps needed to build + publish the Java binaries

**Comment by pawelprazak** [comment]
Probably related to https://github.com/pulumi/pulumi-java/issues/536
