### ISSUE TITLE
Broken javadoc links

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-java#595]
### What happened?

Community member noticed that search was broken in java
https://www.pulumi.com/docs/reference/pkg/java/

### Steps to reproduce

clicking on a link from the search box leads to a 404

### Expected Behavior

should link to:
https://www.pulumi.com/docs/reference/pkg/java/com/pulumi/asset/AssetArchive.html

### Actual Behavior

actual: https://www.pulumi.com/docs/reference/pkg/java/undefined/com/pulumi/asset/AssetArchive.html

### Additional context

Workaround https://github.com/pulumi/docs/pull/7520 but we should fix the root cause.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by cnunciato** [comment]
Looks like this also happens here:
https://javadoc.io/doc/com.pulumi/aws/latest/index.html
