### ISSUE TITLE
Release awsx 1.0.0-beta.{2,3,4,5,6}

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-java#613]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

- [x] tag 1.0.0.-beta.2
- [x] https://github.com/pulumi/pulumi-java/pull/619
- [x] https://github.com/pulumi/pulumi-java/pull/620
- [x] https://github.com/pulumi/pulumi-java/pull/621
- [x] https://github.com/pulumi/pulumi-java/pull/622
- [x] close staging maven repo

**Comment by stack72** [comment]
We are now on beta.6 ;)

**Comment by t0yv0** [comment]
Updated to release all of those. It's not bad but not fully automated yet hence need this reminder. Thanks.
