### ISSUE TITLE
Do not panic when the type of a property in resource outputs doesn't match 

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-java#643]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

The motivation behind it can be found in:
https://github.com/pulumi/pulumi/issues/7329

There is also a PR implementing it for C#.

https://github.com/pulumi/pulumi/pull/8286

The fix proceed with a null / default value and a warning in place of an error. This makes some programs succeed.

Consider implementing the same here.

**Comment by pawelprazak** [comment]
Ideally we'd have as complete as possible test coverage for this change, since this requires refactoring the Converter/Deserializer, and I'm always worried about changing code there ;)

**Comment by mikhailshilkov** [comment]
This sounds important to me, should we add to the epic?

**Comment by pawelprazak** [comment]
@Frassle had a very interesting idea https://github.com/pulumi/pulumi/issues/7329#issuecomment-947681139
I'm just not sure how feasible it would be to implement.

**Comment by t0yv0** [comment]
The straightforward approach would be to proceed with `Output.ofNullable(null)` in case of error. It would work if unused, and it would throw NPE if used. If we want to improve the NPE and throw something more meaningful, we could explore the path of:

```
Output.of(CompletableFuture.ofException(new ProviderTypeMismatchException(...)))
```

This would throw a better exception. Without special care, this would still make the program fail even if unused though because we have the machinery to note exceptions in every Output. That would have to be special cased, either ignoring exceptions of ProviderTypeMismatchException or having a flag to disable the machinery in this call of `Output.of`.

**Comment by mikhailshilkov** [comment]
I think .NET does something like the former option?
