### ISSUE TITLE
Upgrade grpc-core Java SDK dependency to avoid CWE-404

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-java#695]
### What happened?

https://ossindex.sonatype.org/vulnerability/sonatype-2021-0818?component-type=maven&component-name=io.grpc%2Fgrpc-core&utm_source=ossindex-client&utm_medium=integration&utm_content=1.7.0

CWE-404: Improper Resource Shutdown or Release

Note that previously we noticed some issues with tests not passing after upgrading gRPC deps, so this might need some work.

### Steps to reproduce

-

### Expected Behavior

-

### Actual Behavior

-

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by pawelprazak** [comment]
Not sure I understand this one, do I understand correctly it was reverted?
https://github.com/grpc/grpc-java/pull/8361

**Comment by t0yv0** [comment]
This is now fixed (dep upgraded) + detailed workaround for the minimal example in https://github.com/pulumi/pulumi-java/pull/806
