### ISSUE TITLE
`pulumi convert` Java code-gen uses `id()` but should be `getId()`

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-java#698]
The code-generation leveraged by `pulumi convert` emits references to `.id()` for any resources referenced, e.g.

```java
        var prodSubnetPrivate1 = new Subnet("prodSubnetPrivate1", SubnetArgs.builder()        
            .vpcId(prodVpc.id())
            .cidrBlock("10.192.20.0/24")
            .mapPublicIpOnLaunch(false)
            .availabilityZone(availabilityZones.apply(getAvailabilityZonesResult -> getAvailabilityZonesResult.names()[1]))
            .build());
```

but I believe it should be emitting `.getId()` based on:

https://github.com/pulumi/pulumi-java/blob/5cd9786feb4ce575431baa81e92e55d0bd9b58f7/sdk/java/pulumi/src/main/java/com/pulumi/resources/CustomResource.java#L94-L96

**Comment by mikhailshilkov** [comment]
We should probably do https://github.com/pulumi/pulumi-java/issues/704 instead
