### ISSUE TITLE
Change getId() to id()

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-java#704]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

We renamed all property getters to remove `get` from the name, but forgot to do the same for the `getId()` method: https://github.com/pulumi/pulumi-java/blob/5cd9786feb4ce575431baa81e92e55d0bd9b58f7/sdk/java/pulumi/src/main/java/com/pulumi/resources/CustomResource.java#L94-L96

We should go ahead and do that. It's a breaking change but we now is the best time we can do it yet.

**Comment by pawelprazak** [comment]
FYI this might require docs, example and templates changes.

**Comment by mikhailshilkov** [comment]
Sure, that's reasonable

**Comment by pawelprazak** [comment]
As it turns out this impacts codegen with the name collisions, will adjust the codegen accordingly.

**Comment by pawelprazak** [comment]
Added a follow up issue to cleanup the deprecated methods: https://github.com/pulumi/pulumi-java/issues/769
