### ISSUE TITLE
Changes in packages for Java SDK

### ISSUE THREAD

**Issue by salaboy** [pulumi/pulumi-java#774]
### What happened?

I've created a new `pulumi kubernetes-java` project and the packages used for the Kubernetes objects had been moved to a different package. 

Package change from: `import com.pulumi.kubernetes.apps_v1` to `import com.pulumi.kubernetes.apps.v1`

### Steps to reproduce

Create new `kubernetes-java` pulumi app

### Expected Behavior

Use the correct packages for the kube APIs

### Actual Behavior

wrong package is used

### Versions used

CLI          
Version      3.37.2
Go Version   go1.17.12
Go Compiler  gc

Plugins
NAME  VERSION
java  unknown

Host     
OS       darwin
Version  12.4
Arch     x86_64

This project is written in java: java='openjdk 17.0.2 2022-01-18' javac='17.0.2' maven='Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)'

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by salaboy** [comment]
Fixing the package import doesn't solve the problem as it seems to be a dependency chain issue. When manually updating to the new packages I am getting this issue: 

```

java.lang.UnsupportedOperationException: Convert [com.pulumi.kubernetes.apps.v1.Deployment.spec]: Error converting 'com.google.common.collect.RegularImmutableMap' to 'TypeShape{type=class com.pulumi.kubernetes.apps.v1.outputs.DeploymentSpec, parameters=[]}'. argument type mismatch

```

So I thought about sharing which maven dependencies are being used: 

<img width="449" alt="Screenshot 2022-08-04 at 10 34 43" src="https://user-images.githubusercontent.com/271966/182815001-ded70edd-be7a-44f8-9af3-1051c5920680.png">

I wonder if there is a way just to get a stable `com.pulumi:kubernetes` package.

**Comment by stack72** [comment]
Hi @salaboy 

Thanks for opening this :) Would you try this package? https://mvnrepository.com/artifact/com.pulumi/kubernetes/3.20.2 I believe that this is ok?

Paul

**Comment by salaboy** [comment]
Yeah.. let me give that a try

**Comment by salaboy** [comment]
@stack72 do you know which version of com.pulumi:pulumi version goes with 3.20.2 ?

**Comment by salaboy** [comment]
@stack72 `pulumi up` with version 3.20.2 gives the following error: 

```
error: no resource plugin 'pulumi-resource-kubernetes' found in the workspace at version v3.20.2 or on your $PATH, install the plugin using `pulumi plugin install resource kubernetes v3.20.2`
```

I was expecting that to be done automatically

**Comment by salaboy** [comment]
and after installing the plugin.. I am still getting: 

```
Diagnostics:
  pulumi:pulumi:Stack (platform-api-java-platform-java):
    error: Running program [PID: 23258](/Users/msalatino/.sdkman/candidates/java/current/bin/java -classpath /usr/local/Cellar/maven/3.8.5/libexec/boot/plexus-classworlds-2.6.0.jar -Dclassworlds.conf=/usr/local/Cellar/maven/3.8.5/libexec/bin/m2.conf -Dmaven.home=/usr/local/Cellar/maven/3.8.5/libexec -Dlibrary.jansi.path=/usr/local/Cellar/maven/3.8.5/libexec/lib/jansi-native -Dmaven.multiModuleProjectDirectory=/Users/msalatino/code/fmtok8s/from-monolith-to-k8s/platform/pulumi/java/platform-api-java org.codehaus.plexus.classworlds.launcher.Launcher --no-transfer-progress compile exec:java) failed with an unhandled exception:
    java.lang.UnsupportedOperationException: Convert [com.pulumi.kubernetes.apps.v1.Deployment.spec]: Error converting 'com.google.common.collect.RegularImmutableMap' to 'TypeShape{type=class com.pulumi.kubernetes.apps.v1.outputs.DeploymentSpec, parameters=[]}'. argument type mismatch
```

**Comment by salaboy** [comment]
I am sure that it is my fault, hence I am sharing my project here: https://github.com/salaboy/from-monolith-to-k8s/tree/main/platform/pulumi/java/platform-api-java

**Comment by stack72** [comment]
ok, this REALLY helps :) Thank you for such a detailed report! I will get someone to have a look :)

Paul

**Comment by stack72** [comment]
@pawelprazak any chance you can have a look here?

**Comment by pawelprazak** [comment]
I'm sorry, we might have a regression (and a gap in tests).

Reverting kubernetes provider to `3.19.1` and using old imports works around the issue.

I'm working on a real fix.

**Comment by t0yv0** [comment]
Bumping into this also. Incidentally, `pulumi new java-kubernetes` is currently broken. Downgrading to 3.19.1 works. Thanks Pawel for picking this up. This seems to work for me:

```
   export PULUMI_JAVA_SDK_VERSION=0.5.2
   export PULUMI_KUBERNETES_PROVIDER_SDK_VERSION=3.19.1
   make test_template.kubernetes-java
```

**Comment by pawelprazak** [comment]
the bot autofixed, but the change needs to be released for proper fix, not sure if we should reopen

**Comment by t0yv0** [comment]
We shouldn't reopen. We close issues and they get released with a bit of delay shortly after.

**Comment by salaboy** [comment]
@pawelprazak @t0yv0 @stack72 thanks for checking this out.. I wanted to make sure that it wasn't a problem on my end. @pawelprazak any idea when this is going to be released?

**Comment by t0yv0** [comment]
I think the fix is part of https://github.com/pulumi/pulumi-java/releases/tag/v0.5.3 release yesterday.
