### ISSUE TITLE
Codegen should escape resource methods only on resource classes

### ISSUE THREAD

**Issue by pawelprazak** [pulumi/pulumi-java#787]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently every getter and setter is escaped to avoid collision with methods inherited from Resource class family, but should only apply to the Resource child classes, not all classes.

This is the current entry point to the escape logic:
![image](https://user-images.githubusercontent.com/48874/184141710-0213450c-a526-48c6-adbc-b007e58615d4.png)

Found during this PR: #766 

Ideas for a clean implementation that would differentiate between resource and non-resource classes very much welcome :)

**Comment by t0yv0** [comment]
Labelling as breaking, so we need to turn this around before GA. Thank you!
