### ISSUE TITLE
Pulumi Java CDK example not present

### ISSUE THREAD

**Issue by nagkumar** [pulumi/pulumi-java#831]
Currently, there is no Java example to use pulumi with AWS CDK, this page also does not have any java+CDK code

https://www.pulumi.com/blog/pulumi-universal-iac/

please add one.

**Comment by stack72** [comment]
Hi @nagkumar 

CDK has no support for anything outside of TypeScript at this time.

Paul

**Comment by lukehoban** [comment]
Adding support for all languages (including Java) to AWS CDK on Pulumi is being tracked in https://github.com/pulumi/pulumi-cdk/issues/49.
