### ISSUE TITLE
Java Unit test code not working as AMI no more available in aws

### ISSUE THREAD

**Issue by nagkumar** [pulumi/pulumi-java#832]
### What happened?

https://github.com/pulumi/pulumi-java/blob/main/tests/examples/testing-unit-java/src/main/java/com/pulumi/example/unittest/WebserverInfra.java

fails as ami("ami-c55673a0") not found,

need to change the logic similar to its typescript version as in 

that uses this logic to dynamically get the lates AMI version like this

```
const amiId = aws.ec2.getAmi({
    mostRecent: true,
    owners: ["099720109477"],
    filters: [{
        name: "name",
        values: ["ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-*"],
    }],
}).then(ami => ami.id);
```

### Steps to reproduce

run the example 

https://github.com/pulumi/pulumi-java/tree/main/tests/examples/testing-unit-java with `pulumi up`

### Expected Behavior

It should start a webserver without any errors

### Actual Behavior

fails to find the ami image

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dixler** [comment]
hi, thanks for reporting this. I will take a look.

**Comment by dixler** [comment]
So I've taken a look at this and asked around. Our tests are oriented on checking that pulumi java isn't broken so they don't fully test the test's integration with AWS.

I'm going to close this issue, but I'll direct you more to https://github.com/pulumi/examples/tree/master/aws-java-webserver as it's more extensive and complete and has a readme in it, but I'm sure you're probably past this point as it's been a few weeks.
