### ISSUE TITLE
Get Event Hub Shared Access Keys fail due to pulumi forcing alias primary and secondary keys to be non null.

### ISSUE THREAD

**Issue by sachintaksande** [pulumi/pulumi-java#839]
### What happened?

Get Event Hub Shared Access Keys fail due to pulumi forcing alias primary and secondary keys to be non null.

### Steps to reproduce

CLI Command: 
az eventhubs eventhub authorization-rule keys list --resource-group my-resource-group namespace-name my-namespace --eventhub-name my-event-hub --name my-shared-key

Response:
{
  "aliasPrimaryConnectionString": null,
  "aliasSecondaryConnectionString": null,
  "keyName": "my-shared-key",
  "primaryConnectionString": "Endpoint=sb://my-namespace.servicebus.windows.net/;SharedAccessKeyName=my-shared-key;SharedAccessKey=xxxxxxxxxx;EntityPath=my-event-hub",
  "primaryKey": “xxxxxxxxxxxx”,
  "secondaryConnectionString": "Endpoint=sb:/my-namespace.servicebus.windows.net/;SharedAccessKeyName=my-shared-key;SharedAccessKey=xxxxxxxxxxxxxxx;EntityPath=my-event-hub",
  "secondaryKey": “xxxxxxxxxxx”xxxx
}

Pulumi Code:

EventhubFunctions.listEventHubKeys(ListEventHubKeysArgs.builder()
        .resourceGroupName(Output.of("my-resource-group"))
        .namespaceName(Output.of("my-namespace"))
        .eventHubName(Output.of("my-event-hub"))
        .authorizationRuleName(Output.of("my-shared-key"))
        .build());

Error after pulumi up:

java.lang.UnsupportedOperationException: Convert [azure-native:eventhub:listEventHubKeys result]: Error converting 'com.google.common.collect.RegularImmutableMap' to 'TypeShape{type=class com.pulumi.azurenative.eventhub.outputs.ListEventHubKeysResult, parameters=[]}'. Unexpected exception: null
        at com.pulumi.serialization.internal.Converter.convertObjectUntyped(Converter.java:119)
        at com.pulumi.serialization.internal.Converter.convertValue(Converter.java:86)
        at com.pulumi.deployment.internal.DeploymentImpl$Invoke.parseInvokeResponse(DeploymentImpl.java:482)
..............
    Caused by: java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:222)
        at com.pulumi.azurenative.eventhub.outputs.ListEventHubKeysResult$Builder.aliasSecondaryConnectionString(ListEventHubKeysResult.java:134)
        ... 31 more

### Expected Behavior

Successful with no exception

### Actual Behavior

Exception because the alias secondary key is assumed to be non null.

### Output of `pulumi about`

CLI          
Version      3.39.3
Go Version   go1.19.1
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.74.0
java          unknown

Host     
OS       darwin
Version  12.6
Arch     x86_64

This project is written in java: executable='/usr/bin/java' version='openjdk 14.0.2 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-46)
OpenJDK 64-Bit Server VM (build 14.0.2+12-46, mixed mode, sharing)' maven='Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)' java='/usr/bin/java' javac='14.0.2'

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
Thank you for reporting this issue! It appears that the root cause here is the same as in https://github.com/pulumi/pulumi-java/issues/821 - Pulumi Java SDK accidentally regressed in tolerating missing data from providers. I'm working on a fix and will release an updated version shortly and ask you to try to see if this fixes the problem. If you'd like me to try to reproduce, it would be very helpful if you could include a more complete example.

**Comment by sachintaksande** [comment]
Thanks @t0yv0 . The fix you provided looks correct fix to me. I haven't checked if this particular issue is addressed or not. I will check it and come back if it still fails with the latest revision.

**Comment by t0yv0** [comment]
You can use this version to test the fix:

```
    <dependency>
      <groupId>com.pulumi</groupId>
      <artifactId>pulumi</artifactId>
      <version>0.6.0</version>
    </dependency>
```

**Comment by sachintaksande** [comment]
Hi @t0yv0 , the version 0.6.0 works for me as expected. Thank you for the awesome support in resolving the issue!
