### ISSUE TITLE
Gradle executor is not detected if only build.gradle.kts file is present

### ISSUE THREAD

**Issue by sndl** [pulumi/pulumi-java#846]
https://github.com/pulumi/pulumi-java/blob/af0e43990042b9649a8f04a4aed7902bce8e8212/pkg/internal/executors/executor_gradle.go#L88-L92

The code above is used to detect an executor, and if I have only `build.gradle.kts` file in my project, then it falls through to `sbt` executor

Also, this function might be worth looking at as well:
https://github.com/pulumi/pulumi-java/blob/af0e43990042b9649a8f04a4aed7902bce8e8212/pkg/internal/executors/executor_gradle.go#L58-L62

**Comment by t0yv0** [comment]
Thank you for noting this. Would you be interested in contributing a PR? Perhaps something as easy as adding `build.gradle.kts`  to the markers list would work?

**Comment by ilya40umov** [comment]
I have run into this problem in a few projects now, and in most cases adding an empty `settings.gradle.kts` was doing the trick. However, the problem now is that for a multi-module project these `settings.gradle.kts` are causing Gradle to think that this a root module (while in fact it's sub-module of a multi-module project).

**Comment by mklueh** [comment]
Facing the same problem within a monorepo, where all the Gradle stuff is under /root and the infrastructure is in /infra

An empty settings.gradle.kts did not help and produces

> Error(error: failed to discover plugin requirements: language host could not determine Pulumi packages: could not find ./gradlew, gradle on the $PATH: exec: "gradle": executable file not found in %PATH%

**Comment by aweiher** [comment]
indeed, an empty `settings.gradle.kts` helps as it is part of the `gradleRootMarkers` posted

without it the error is as follows: 

> error: failed to discover plugin requirements: language host could not determine Pulumi packages: could not find ./sbt, sbt on the $PATH: exec: "sbt": executable file not found in $PATH
