### ISSUE TITLE
Sync PCL files from `pulumi/yaml`

### ISSUE THREAD

**Issue by aq17** [pulumi/pulumi-java#860]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Similar to https://github.com/pulumi/pulumi-yaml/issues/251 – we want to test the latest PCL generated files from YAML, converting them to Java

**Comment by RobbieMcKinstry** [comment]
@aq17 it looks like Pulumi Bot auto-generates a PR to address this? 
https://github.com/pulumi/pulumi-java/pull/861
Looks like we can merge and close. Can you confirm?

**Comment by aq17** [comment]
@RobbieMcKinstry yup this is good to go
