### ISSUE TITLE
Ability to invoke deployment from inside Java program

### ISSUE THREAD

**Issue by cowwoc** [pulumi/pulumi-java#868]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

----------

Similar to https://github.com/pulumi/pulumi/pull/3479#issuecomment-560134673 I think you will run across a lot of resistance if you force people to run their Java scripts from command-line.

For my part, I want to be able to invoke deployments from within a JVM because I want my application to trigger deployment on-demand if its resources are missing at runtime.

**Comment by RobbieMcKinstry** [comment]
Aha! A colleague pointed me to an existing issue for AA support for Java: https://github.com/pulumi/pulumi/issues/8315

If indeed AA support would satisfy your need, I'll close this as a duplicate. 😄

**Comment by cowwoc** [comment]
Hi @RobbieMcKinstry 

Yes, this issue is a duplicate.
