### ISSUE TITLE
Release 0.7.0 is broken

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/pulumi-java#919]
### What happened?

Upgrading to 0.7.0 causes a non-buildable Java SDK.

This seems to be caused by the `0.7.0` release actually having been released as `0.7.0+dirty`: https://repo.maven.apache.org/maven2/com/pulumi/pulumi/

### Steps to reproduce

1. Upgrade java gen binary to 0.7.0
2. Re-generate Java SDK
3. Build the Java SDK

### Expected Behavior

Build should pass

### Actual Behavior

```
/Users/dan/Dev/pulumi-aws/bin/pulumi-java-gen generate --schema provider/cmd/pulumi-resource-aws/schema.json --out sdk/java  --build gradle-nexus
cd sdk/java/ && \
                echo "module fake_java_module // Exclude this directory from Go tools\n\ngo 1.17" > go.mod && \
                gradle --console=plain build
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find com.pulumi:pulumi:0.7.0.
     Searched in the following locations:
       - file:/Users/dan/.m2/repository/com/pulumi/pulumi/0.7.0/pulumi-0.7.0.pom
       - https://maven-central.storage-download.googleapis.com/maven2/com/pulumi/pulumi/0.7.0/pulumi-0.7.0.pom
       - https://repo.maven.apache.org/maven2/com/pulumi/pulumi/0.7.0/pulumi-0.7.0.pom
     Required by:
         project :
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
We released 0.7.1 to resolve the issue.
