### ISSUE TITLE
docs: Missing guide on unit testing

### ISSUE THREAD

**Issue by abhinav** [pulumi/pulumi-java#979]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

pulumi-java tracking issue for #2480.

Docs at https://www.pulumi.com/docs/guides/testing/unit/ don't specify how to unit test in Java.

### Affected area/feature

docs

**Comment by mikhailshilkov** [comment]
Now tracked in https://github.com/pulumi/pulumi-java/issues/1315
