### ISSUE TITLE
Generated Gradle build files do not work on Version 8

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-java#993]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Recently GitHub auto-upgraded Gradle to 8.0, causing providers build failure. We are trying to pin to 7.6. 

Symptom is :

Could not set unknown property 'classifier' for task ':sourcesJar' of type org.gradle.api.tasks.bundling.Jar.

For the moment we use the default Gradle template from pulumi-java-gen in most places, and if that could be fixed up it'd be ideal to roll out and unpin Gradle.

See https://github.com/pulumi/ci-mgmt/issues/351

**Comment by thomas11** [comment]
See also pulumi/pulumi-azure-native#2262. As noted there, `classifier` should be `archiveClassifier` now.

**Comment by dixler** [comment]
@t0yv0 this sounded like a p1. I see that you've closed https://github.com/pulumi/ci-mgmt/issues/351. Is this still a priority?

**Comment by t0yv0** [comment]
I'm not sure that upgrading to the latest version of the Gradle toolchain is a P1 because we're similarly lagging behind on toolchain versions across say .NET but I'll defer to how y'all prioritize. The fixup should be relatively simple I hope.
